spring:
  application:
    name: demo
server:
  port: 6006
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6002/eureka/
feign:
  hystrix:
    enable: true
# 断路器配置
hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 100
          thread:
            timeoutInMilliseconds: 50000 #缺省为1000
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 100